---

backup_sources:
  - "{{ ansible_user_dir }}/dotfiles"
  - "{{ ansible_user_dir }}/projects"
  - "{{ ansible_user_dir }}/.bash_history"
  - "{{ ansible_user_dir }}/.python_history"
  - "{{ ansible_user_dir }}/.zsh_history"
  - "/mnt/share/archive"
  - "/boot/"

backup_repos:
  - "/mnt/share/backup"
  - "b2:backups-joren-vrancken"
