---

backup_sources:
  - "{{ ansible_user_dir }}/dotfiles"
  - "{{ ansible_user_dir }}/projects"
  - "{{ ansible_user_dir }}/.bash_history"
  - "{{ ansible_user_dir }}/.python_history"
  - "{{ ansible_user_dir }}/.zsh_history"

backup_repos:
  - "b2:backups-joren-vrancken"
