---

has_sudo: yes

# Custom variables
is_laptop: yes
monitors:
  - "eDP"

ssh_public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4yeSD0yzvS3g6tJnzNMb/vxZvy2DZFdULksqgVMJZLovJ9x6YQuocPDiM//DBzwMsPrchXG3XkaJcCuCZ2DTQcL7RWQiwb3YvZZHDiUQNV8lNEFds96R/TunAJ5pudnkM9IXDZAVjAxpLHEHtWGdONeoOmdWrbJMZRdzmpnkONH7bnK9knRUASldmJxNPP03VBaEZp2+K0wgC1UFR+Nr+wnuHyJulNw/EAlCpbE6uqGjIdA0VukYDV3icRAx0xHCda68nSbRE4V+vckwWDkWsaUrD2O+Dg2EiwXrFxBMkqhu86yN3IlfmlI008u+gVn8zywV3J20hdmeqOCZGUP+V joren@JorenLaptop"

# boot parameters: iommu=soft acpi_backlight=vendor amdgpu.dc=0
