---
sudo: false
language: "python"

install:
  - "pip install -U pip wheel"
  - "pip install -r requirements_travis.txt"

before_script:
  - "echo placeholder >> password_file"

script:
  - "ansible-playbook pc.yml --syntax-check"
  - "ansible-playbook remote.yml --syntax-check"
  - "ansible-lint pc.yml"
  - "ansible-lint remote.yml"

cache: "pip"

env:
  global:
    - "VAULT=placeholder_vault"

notifications:
  email:
    on_success: "never"
    on_failure: "always"
