---

jobs:
    include:

        - &syntax_check
          stage: "lint" 
          sudo: false
          language: "python"
          python: "3.6"
          cache: "pip"
          env: "PLAYBOOK=pc.yml ENVIRONMENT=production"
          before_install:
              - "pip install --upgrade pip wheel"
          install:
              - "pip install --progress-bar=off --upgrade ansible"
          before_script:
              - "chmod 700 $TRAVIS_BUILD_DIR"
              - "sed -i 's/^vault_password_file/# &/' ansible.cfg"
          script:
              - "ansible-playbook ${PLAYBOOK} --inventory-file=environments/${ENVIRONMENT}/hosts --syntax-check" 

        - <<: *syntax_check
          env: "PLAYBOOK=remote.yml ENVIRONMENT=production"

        - <<: *syntax_check
          env: "PLAYBOOK=travis.yml ENVIRONMENT=testing"

        - <<: *syntax_check
          env: ""
          install:
              - "pip install --progress-bar=off --upgrade ansible-lint"
          script:
              - "ansible-lint *.yml"

        - stage: "playbook"
          sudo: "required"
          language: "generic"
          services:
              - "docker"
          env:
              - "NAME_DOCKER=travis_test DIRECTORY_WORKING=/ansiblei ANSIBLE_USER_NAME=travis ANSIBLE_USER_PASSWORD=travis"
          before_install:
              - "docker pull pritunl/archlinux:latest"
              - >
                  docker run 
                  --rm 
                  --detach 
                  --name=${NAME_DOCKER} 
                  --hostname=${NAME_DOCKER} 
                  --volume=${TRAVIS_BUILD_DIR}:${DIRECTORY_WORKING} 
                  --workdir=${DIRECTORY_WORKING} 
                  pritunl/archlinux:latest 
                  tail -f /dev/null
          install:
              - "docker exec ${NAME_DOCKER} pacman -Sy --noconfirm --needed ansible sudo"
          before_script:
              - "chmod 700 $TRAVIS_BUILD_DIR"
              - "sed -i 's/^vault_password_file/# &/' ansible.cfg"
              - "docker exec ${NAME_DOCKER} groupadd users"
              - "docker exec ${NAME_DOCKER} groupadd wheel"
              - "docker exec ${NAME_DOCKER} /bin/bash -c \"echo '%wheel ALL=(ALL) ALL' >> /etc/sudoers\""
              - "docker exec ${NAME_DOCKER} useradd -m -G wheel ${ANSIBLE_USER_NAME}"
              - "docker exec ${NAME_DOCKER} /bin/bash -c \"echo ${ANSIBLE_USER_NAME}:${ANSIBLE_USER_PASSWORD} | chpasswd\""
          script:
              # Run the test playbook twice, to check it works on a fresh host and a fully installed host
              - "docker exec ${NAME_DOCKER} ansible-playbook --inventory-file=environments/testing/hosts -vv travis.yml"
              - "docker exec ${NAME_DOCKER} ansible-playbook --inventory-file=environments/testing/hosts -vv travis.yml"
          after_script:
              - "docker stop ${NAME_DOCKER}"

notifications:
  email:
    on_success: "never"
    on_failure: "always"
