---
sudo: false
language: "python"

install:
  - "pip install -U pip wheel"
  - "pip install -r requirements_travis.txt"

before_script:
  - "sed -i 's/^vault_password_file/# &/' ansible.cfg"

script:
  - "ansible-playbook pc.yml --syntax-check"
  - "ansible-playbook remote.yml --syntax-check"
  - "ansible-lint pc.yml"
  - "ansible-lint remote.yml"

cache: "pip"

notifications:
  email:
    on_success: "never"
    on_failure: "always"
