---
language: "python"

install:
  - "pip install ansible"
  - "pip install ansible-lint"

before_script:
  - "echo placeholder >> password_file"

script:
  - "ansible-playbook pc.yml --syntax-check"
  - "ansible-playbook remote.yml --syntax-check"
  - "ansible-lint pc.yml"
  - "ansible-lint remote.yml"

env:
  global:
    - VAULT="placeholder_vault"
