---

extends: "default"

ignore:
  - ".git/"
  - ".venv/"
  - "vault.yaml"

rules:
  line-length: false
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
