---

- name: "Run global configuration"
  hosts: "all"
  roles:
      - role: "common"
        tags: "common"

      - role: "users"
        tags:
            - "user"
            - "users"

      - role: "network"
        tags: "network"

      - role: "packages"
        tags: "packages"

      - role: "ssh"
        tags: "ssh"

      - role: "gnupg"
        tags:
            - "gnupg"
            - "gpg"
            - "gpg2"
            - "pgp"

      - role: "git"
        tags: "git"

      - role: "zsh"
        tags: "zsh"

      - role: "vim"
        tags: "vim"

      - role: "docker"
        tags: "docker"

      - role: "backups"
        tags:
            - "backup"
            - "backups"

- name: "Configure laptop"
  hosts: "druif"
  roles:
      - role: "sway"
        tags: "sway"

