---

- name: "Run global configuration"
  hosts: "all"
  roles:
      - role: "common"
        tags: "common"

      - role: "users"
        tags:
            - "user"
            - "users"

      - role: "network"
        tags: "network"

      - role: "packages"
        tags: "packages"

      - role: "ssh"
        tags: "ssh"

      - role: "gnupg"
        tags:
            - "gnupg"
            - "gpg"
            - "gpg2"
            - "pgp"

      - role: "git"
        tags: "git"

      - role: "zsh"
        tags: "zsh"

      - role: "vim"
        tags: "vim"

      - role: "backups"
        tags:
            - "backup"
            - "backups"

- name: "Configure laptop"
  hosts: "druif"
  roles:
      - role: "sway"
        tags: "sway"

- name: "Setup dnsmasq"
  hosts: "nameservers"
  roles:
      - role: "dnsmasq"
        tags: "dnsmasq"

- name: "Setup Unifi Controllers"
  hosts: "unifi_controllers"
  roles:
      - role: "docker"
        tags: "unifi"
        vars:
            project:
                name: "unifi"
                directories:
                    - "mongo/db/"
                    - "mongo/configdb/"
                    - "config/"

- name: "Setup Plex Controllers"
  hosts: "media_servers"
  roles:
      - role: "docker"
        tags: "plex"
        vars:
            project:
                name: "plex"
                directories:
                    - "config/"
                    - "transcode/"
                    - "/srv/share/plex/"
                    - "/srv/share/plex/movies/"
                    - "/srv/share/plex/tv-shows/"

- name: "Setup Transmission"
  hosts: "seedboxes"
  roles:
      - role: "docker"
        tags: "transmission"
        vars:
            project:
                name: "transmission"
                directories:
                    - "/srv/share/transmission/"

- name: "Setup Samba server"
  hosts: "fileservers"
  roles:
      - role: "samba"
        tags: "samba"
