---

- name: "Run global configuration"
  hosts: "all"
  roles:
      - role: "common"
        tags: "common"

      - role: "users"
        tags:
            - "user"
            - "users"

      - role: "ssh"
        tags: "ssh"

      - role: "packages"
        tags: "packages"

      - role: "git"
        tags: "git"

      - role: "zsh"
        tags: "zsh"

      - role: "vim"
        tags: "vim"

- name: "Configure laptop"
  hosts: "druif"
  roles:

      - role: "gnupg"
        tags:
            - "gnupg"
            - "gpg"
            - "gpg2"
            - "pgp"

      - role: "sway"
        tags: "sway"

      - role: "backups"
        tags:
            - "backup"
            - "backups"

- name: "Setup Unifi Controllers"
  hosts: "unifi_controllers"
  roles:
      - role: "docker"
        tags: "unifi"
        vars:
            project_name: "unifi"
            users:
                mongo:
                    name: "mongo"
                    uid: "600"
                    gid: "600"
                    home: "mongo"
                    comment: "MongoDB"
                    extra_directories:
                        - "db"
                        - "dbconfig"
                unifi:
                    name: "unifi"
                    uid: "601"
                    gid: "601"
                    home: "config"
                    comment: "Unifi Controller"

- name: "Setup Plex Controllers"
  hosts: "media_servers"
  roles:
      - role: "docker"
        tags: "plex"
        vars:
            project_name: "plex"
            users:
                plex:
                    name: "plex"
                    uid: "602"
                    gid: "602"
                    home: "config"
                    comment: "Plex Media Server"
                    extra_directories:
                        - "transcode"
                        - "/srv/share/plex/"
                        - "/srv/share/plex/movies/"
                        - "/srv/share/plex/tv-shows/"

- name: "Setup Transmission"
  hosts: "seedboxes"
  roles:
      - role: "docker"
        tags: "transmission"
        vars:
            project_name: "transmission"
            users:
                transmission:
                    name: "transmission"
                    uid: "603"
                    gid: "603"
                    home: "config"
                    comment: "Transmission"
                    extra_directories:
                        - "/srv/share/transmission/"

- name: "Setup NFS"
  hosts: "fileservers"
  roles:
      - role: "nfs"
        tags: "nfs"
