---

- name: "Configure laptop"
  hosts: "druif"
  roles:
      - role: "common"
        tags: "common"

      - role: "ssh"
        tags:
            - "ssh"
            - "openssh"

      - role: "gnupg"
        tags:
            - "gnupg"
            - "gpg"
            - "gpg2"
            - "pgp"

      - role: "zsh"
        tags: "zsh"

      - role: "xorg"
        tags: "xorg"

      - role: "i3"
        tags: "i3"

      - role: "polybar"
        tags: "polybar"

      - role: "vim"
        tags: "vim"

      - role: "backups"
        tags:
            - "backup"
            - "backups"

      - role: "packages"
        tags:
            - "packages"
            - "git"
            - "docker"

- name: "Configure hosts at home"
  hosts: "homelab"
  roles:
      - role: "common"
        tags: "common"

      - role: "zsh"
        tags: "zsh"

      - role: "vim"
        tags: "vim"

      - role: "packages"
        tags: "packages"

- name: "Setup qBittorrent"
  hosts: "qbittorrent"
  roles:
      - role: "qbittorrent"
        tags: "qbittorrent"

- name: "Setup Netdata on parents"
  hosts: "netdata_parents"
  roles:
      - role: "netdata"
        vars:
            netdata_host_type: "parent"
        tags:
            - "netdata"
            - "netdata-parents"
            - "netdata-parent"

- name: "Setup Netdata on children"
  hosts: "netdata_children"
  roles:
      - role: "netdata"
        vars:
            netdata_host_type: "child"
        tags:
            - "netdata"
            - "netdata-children"
            - "netdata-child"
