---

- name: "Run global configuration"
  hosts: "all"
  roles:
      - role: "common"
        tags: "common"

      - role: "users"
        tags:
            - "user"
            - "users"

      - role: "packages"
        tags: "packages"

      - role: "zsh"
        tags: "zsh"

      - role: "vim"
        tags: "vim"

- name: "Configure laptop"
  hosts: "druif"
  roles:
      - role: "ssh"
        tags:
            - "ssh"
            - "openssh"

      - role: "gnupg"
        tags:
            - "gnupg"
            - "gpg"
            - "gpg2"
            - "pgp"

      - role: "sway"
        tags: "sway"

      - role: "backups"
        tags:
            - "backup"
            - "backups"

- name: "Setup Unifi Controllers"
  hosts: "unifi_controllers"
  roles:
      - role: "docker"
        tags: "unifi"
        vars:
            project_name: "unifi"
            users:
                mongo:
                    name: "mongo"
                    uid: "600"
                    gid: "600"
                    home: "mongo"
                    comment: "MongoDB"
                    extra_directories:
                        - "db"
                        - "dbconfig"
                unifi:
                    name: "unifi"
                    uid: "601"
                    gid: "601"
                    home: "config"
                    comment: "Unifi Controller"

- name: "Setup Plex Controllers"
  hosts: "media_servers"
  roles:
      - role: "docker"
        tags: "plex"
        vars:
            project_name: "plex"
            users:
                plex:
                    name: "plex"
                    uid: "602"
                    gid: "602"
                    home: "config"
                    comment: "Plex Media Server"
                    extra_directories:
                        - "transcode"
                        - "/srv/share/plex/"
                        - "/srv/share/plex/movies/"
                        - "/srv/share/plex/tv-shows/"
