---

- name: "Update pacman cache"
  pacman:
    update_cache: yes
    upgrade: yes

- name: "Install packages"
  pacman:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ common_packages }}"

- name: "Install laptop packages"
  when: "is_laptop"
  pacman:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ laptop_packages }}"

- name: "Install pip packages"
  pip:
    name: "{{ pip_packages }}"
    executable: "{{ item }}"
    state: "present"
    extra_args: "--user"
  with_items:
    - "pip2"
    - "pip3"

- name: "Enable NetworkManager"
  service:
    name: "NetworkManager"
    state: "started"
    enabled: yes
