---

- name: "Combine package lists"
  set_fact:
    packages: "{{ packages_common + packages_host }}"
    packages_aur: "{{ packages_common_aur + packages_host_aur }}"

- name: "Update pacman cache"
  become: yes
  pacman:
    update_cache: yes

- name: "Install packages"
  become: yes
  package:
    name: "{{ packages }}"
    state: "present"

- name: "Show which AUR packages to install"
  when: "packages_common_aur and packages_host_aur"
  debug:
    msg: "Please install {{ item }} on {{ inventory_hostname }}."
  loop: "{{ packages_aur }}"

- name: "Run package specific config"
  import_tasks: "package_config.yaml"
