---

- name: "Update pacman cache"
  become: yes
  pacman:
    update_cache: yes

- name: "Install packages"
  become: yes
  pacman:
    name: "{{ common_packages }}"
    state: "present"

- name: "Install laptop packages"
  when: "is_laptop|default(False, True)"
  become: yes
  pacman:
    name: "{{ laptop_packages }}"
    state: "present"

- name: "Install pip packages"
  pip:
    name: "{{ pip_packages }}"
    executable: "{{ item }}"
    state: "present"
    extra_args: "--user"
  loop:
    - "pip2"
    - "pip3"

- name: "Enable NetworkManager"
  become: yes
  service:
    name: "NetworkManager"
    state: "started"
    enabled: yes
