---

- name: "Install pacman"
  community.general.pacman:
    name:
      - "pacman"
      - "pacman-contrib"

- name: "Install pacman hooks"
  become: true
  block:
    - name: "Enable pacman hooks directory"
      ansible.builtin.lineinfile:
        path: "/etc/pacman.conf"
        line: "HookDir = /etc/pacman.d/hooks/"
        regexp: '^#?HookDir\s*='

    - name: "Create /etc/pacman.d/hooks"
      ansible.builtin.file:
        path: "/etc/pacman.d/hooks"
        state: "directory"
        mode: "0755"
        owner: "root"
        group: "root"

    - name: "Copy hook files"
      ansible.builtin.copy:
        src: "pacman/{{ item }}"
        dest: "/etc/pacman.d/hooks/95-{{ item }}"
        mode: "0755"
        owner: "root"
        group: "root"
      loop:
        - "pacdiff.hook"

- name: "Update pacman cache"
  become: true
  community.general.pacman:
    update_cache: true

- name: "Install packages"
  become: true
  community.general.pacman:
    name: "{{ packages_host + packages_common }}"

- name: "Show which AUR packages to install"
  ansible.builtin.debug:
    msg: "Please install {{ item }} on {{ inventory_hostname }}."
  loop: "{{ packages_host_aur }}"
