---

- name: "Install Xorg"
  become: yes
  package:
    name:
      - "xorg"
      - "rxvt-unicode"
      - "rxvt-unicode-terminfo"
      - "ttf-dejavu"
      - "xterm"
      - "arandr"
      - "xclip"
    state: "present"

- name: "Create .local/bin/"
  file:
    path: "{{ ansible_user_dir }}/.local/bin/"
    state: "directory"
    mode: "0755"

- name: "Copy Xorg user configuration files"
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    mode: "0644"
  loop:
    - "Xresources"
    - "xinitrc"

- name: "Place dock scripts"
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.local/bin/{{ item }}"
    mode: "0755"
  loop:
    - "undock.sh"
    - "dock.sh"

- name: "Setup fonts"
  block:
    - name: "Install fonts"
      package:
        name: "ttf-dejavu"
        state: "present"

    - name: "Create .local/share/fonts/"
      file:
        path: "{{ ansible_user_dir }}/.local/share/fonts/"
        state: "directory"
        mode: "0755"

    - name: "Install nerd font"
      get_url:
        url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DejaVuSansMono/\
          Regular/complete/DejaVu%20Sans%20Mono%20Nerd%20Font%20Complete%20Mono.ttf"
        dest: "{{ ansible_user_dir }}/.local/share/fonts/DejaVu Sans Mono Nerd Font Complete Mono.ttf"
