# set right keyboard layout
setxkbmap -layout us -variant intl

# load .Xrecources
xrdb {{ xresources_location }}

# Disable beep
xset -b

# Screen powersave
# Note: If using this command manually in a shell you may need to prefix it with sleep 1; for it to work correctly
# Source: https://wiki.archlinux.org/index.php/Display_Power_Management_Signaling
sleep 1; xset +dpms
sleep 1; xset dpms 0 0 300

# Set wallpaper
feh --bg-fill --no-xinerama  {{ wallpaper_location }}
{% if not is_laptop and not headless%}

# set keyboard leds
xset led

{% endif %}
exec i3
