---

- name: "Install gnupng"
  become: true
  community.general.pacman:
    name: "gnupg"

- name: "Import PGP key"
  when: "pgp_private_key is defined"
  ansible.builtin.shell: |
    set -o pipefail
    echo {{ pgp_private_key | quote }} | gpg --batch --import
  register: "gnupg_result_private_key_import"
  changed_when: "gnupg_result_private_key_import is defined and 'secret keys imported: 1' in gnupg_result_private_key_import.stderr"

- name: "Create directory"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.gnupg/"
    state: "directory"
    mode: "0700"

- name: "Copy gpg-agent.conf"
  ansible.builtin.copy:
    src: "gpg-agent.conf"
    dest: "{{ ansible_user_dir }}/.gnupg/gpg-agent.conf"
    mode: "0644"
  notify: "Reload gpg-agent"
