---
- name: "Install gnupng"
  when: "has_sudo"
  become: yes
  pacman:
    name: "gnupg"
    state: "present"
    update_cache: yes

- name: "Import PGP key"
  shell: "echo {{ vault_pgp_private_key | quote }} | gpg --batch --import"
  register: "result_private_key_import"
  changed_when: "result_private_key_import is defined and 'secret keys imported: 1' in result_private_key_import.stderr"
