---

- name: "Add SSH public keys to authorized keys"
  when: "hostvars[item].ssh_public_key|default(False)"
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ hostvars[item].ssh_public_key }}"
    state: "present"
  loop: "{{ hostvars|list }}"

- name: "Install SSH keys"
  when: "ssh_public_key is defined and vault_ssh_private_key is defined"
  block:
  - name: "Install public key"
    copy:
      content: "{{ ssh_public_key }}"
      mode: "0600"
      dest: "{{ home_directory }}/.ssh/id_rsa.pub"

  - name: "Install SSH private key"
    copy:
      content: "{{ vault_ssh_private_key }}"
      mode: "0600"
      dest: "{{ home_directory }}/.ssh/id_rsa"

- name: "Enable services"
  become: yes
  when: "has_sudo and not is_laptop|default(False, True) and use_services"
  service:
    name: "sshd"
    state: "started"
    enabled: yes
    daemon_reload: yes

- name: "Disable PasswordAuthentication"
  become: yes
  when: "has_sudo"
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^#?PasswordAuthentication (yes|no)$"
    line: "PasswordAuthentication no"
    state: "present"
  notify:
  - "restart sshd"
