---

- name: "Install packages"
  become: true
  ansible.builtin.package:
    name: "openssh"

- name: "Create .ssh directory"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh/"
    state: "directory"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0700"

- name: "Install SSH key"
  when: "ssh_key is defined"
  block:
    - name: "Install public key"
      ansible.builtin.copy:
        content: "{{ ssh_key.public }}"  # noqa template-instead-of-copy
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0644"
        dest: "{{ ansible_user_dir }}/.ssh/id_ed25519.pub"

    - name: "Install SSH private key"
      ansible.builtin.copy:
        content: "{{ ssh_key.private }}"  # noqa template-instead-of-copy
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"
        dest: "{{ ansible_user_dir }}/.ssh/id_ed25519"

- name: "Copy user config"
  ansible.builtin.copy:
    src: "config"
    mode: "0644"
    dest: "{{ ansible_user_dir }}/.ssh/config"

- name: "Disable SSH password logins"
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^#?PasswordAuthentication (yes|no)$"
    line: "PasswordAuthentication no"

- name: "Start SSH server"
  become: true
  when: "'homelab' in group_names"
  ansible.builtin.systemd:
    name: "sshd"
    state: "started"
    enabled: true
