---

# Ansible connection variables
ansible_user: "travis"
ansible_become_password: "travis"
ansible_connection: "local"

has_sudo: yes

# This key is randomly generated and used nowhere.
ssh_public_key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHE4dUvAluQTDXx+lBu8wNk0kEr5K6tFy0U7qu+c+Ngk"

monitors:
  - "Fake Screen"
