---

- name: "Install zsh and dependencies"
  become: true
  community.general.pacman:
    name:
      - "zsh"
      - "git"
      - "curl"
      - "python-pexpect"
      - "starship"

- name: "Copy ZSH files"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    mode: "0644"
  loop:
    - "zlogin"

- name: "Copy ZSH template files"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    mode: "0644"
  loop:
    - "zshrc"
    - "zshenv"

- name: "Setup oh-my-zsh"
  block:
    - name: "Clone oh-my-zsh"
      ansible.builtin.git:
        repo: "https://github.com/ohmyzsh/ohmyzsh.git"
        dest: "{{ ansible_user_dir }}/.oh-my-zsh/"
        version: "master"

    - name: "Clone zsh-autosuggestions"
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions"
        dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions/"
        version: "master"

- name: "Setup Starship"
  ansible.builtin.template:
    src: "starship.toml.j2"
    dest: "{{ ansible_user_dir }}/.config/starship.toml"
    mode: "0644"

- name: "Change user shell to ZSH"
  when: "'zsh' not in ansible_user_shell"
  ansible.builtin.expect:
    command: "chsh --shell /usr/bin/zsh"
    responses:
      Password: "{{ ansible_become_password }}"
