---

- name: "Install zsh, git and curl"
  when: "has_sudo"
  become: yes
  pacman:
    name: "{{ packages_zsh }}"
    state: "present"
    update_cache: yes

- name: "Check zsh installation"
  command: which zsh
  register: "zsh_installed"
  changed_when: "'/zsh' not in zsh_installed.stdout"
  check_mode: no

- name: "Place zsh files"
  when: "'/zsh' in zsh_installed.stdout"
  block:
  - name: "Copy .zlogin"
    copy:
      src: "zlogin"
      dest: "{{ home_directory }}/.zlogin"

  - name: "Copy .zshenv"
    copy:
      src: "zshenv"
      dest: "{{ home_directory }}/.zshenv"

  - name: "Cloning oh-my-zsh"
    git:
      repo: "https://github.com/robbyrussell/oh-my-zsh"
      dest: "{{ oh_my_zsh_directory }}"
      version: "master"

  - name: "Copy .zshrc"
    template:
      src: "zshrc.j2"
      dest: "{{ home_directory }}/.zshrc"

  - name: "Clone oh-my-zsh autosuggestions"
    git:
      repo: "https://github.com/zsh-users/zsh-autosuggestions"
      dest: "{{ oh_my_zsh_directory }}/custom/plugins/zsh-autosuggestions"
      version: "master"
