---

- name: "Install zsh and dependencies"
  when: "has_sudo"
  become: yes
  package:
    name:
      - "zsh"
      - "git"
      - "curl"
      - "python-pexpect"
    state: "present"

- name: "Check if zsh is installed"
  command: "which zsh"
  changed_when: no
  check_mode: no

- name: "Check if relevant applications are installed"
  vars:
    applications:
      - "ansible"
      - "docker"
      - "poetry"
      - "pip"
      - "sway"
  block:
    - name: "Check if application is installed"
      command: "which {{ item }}"
      register: "which_output"
      changed_when: no
      failed_when: no
      check_mode: no
      loop: "{{ applications }}"

    - name: "Set '_installed' boolean values"
      set_fact:
        "{{ item.item }}_installed": "{{ item.rc == 0 }}"
      loop: "{{ which_output.results }}"

- name: "Copy ZSH files"
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    mode: "0644"
  loop:
    - "zlogin"

- name: "Copy ZSH template files"
  template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    mode: "0644"
  loop:
    - "zshrc"
    - "zshenv"

- name: "Clone oh-my-zsh"
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/"
    version: "master"

- name: "Clone zsh-autosuggestions"
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions/"
    version: "master"

- name: "Copy theme"
  copy:
    src: "prompt.zsh-theme"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/prompt.zsh-theme"
    mode: "0644"

- name: "Install Poetry completions"
  when: "poetry_installed"
  block:
    - name: "Create Poetry plugin directory"
      file:
        state: "directory"
        path: "{{ ansible_user_dir }}/.oh-my-zsh/plugins/poetry/"
        mode: "0755"

    - name: "Generate Poetry completions"
      shell: "poetry completions zsh > {{ ansible_user_dir }}/.oh-my-zsh/plugins/poetry/_poetry"
      changed_when: yes

- name: "Change user shell to ZSH"
  when: "'zsh' not in ansible_user_shell"
  expect:
    command: "chsh --shell /usr/bin/zsh"
    responses:
      Password: "{{ ansible_become_password }}"
