---

- name: "Install zsh and dependencies"
  when: "has_sudo"
  become: yes
  package:
    name:
      - "zsh"
      - "git"
      - "curl"
      - "python-pexpect"
    state: "present"

- name: "Check if zsh is installed"
  command: "which zsh"
  changed_when: no
  check_mode: no

- name: "Check which plugin dependencies are installed"
  vars:
    dependencies:
      - "ansible"
      - "docker"
      - "poetry"
      - "pip"
  block:
    - name: "Check if plugin dependencies are installed"
      command: "which {{ item }}"
      register: "which_output"
      changed_when: no
      failed_when: no
      check_mode: no
      loop: "{{ dependencies }}"

    - name: "Set '_installed' boolean values"
      set_fact:
        "{{ item.item }}_installed": "{{ item.rc == 0 }}"
      loop: "{{ which_output.results }}"

- name: "Copy ZSH configuration files"
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    mode: "0644"
  loop:
    - "zlogin"
    - "zshenv"

- name: "Copy .zshrc"
  template:
    src: "zshrc.j2"
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: "0644"

- name: "Clone oh-my-zsh"
  git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/"
    version: "master"

- name: "Clone zsh-autosuggestions"
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions/"
    version: "master"

- name: "Copy theme"
  copy:
    src: "prompt.zsh-theme"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/prompt.zsh-theme"
    mode: "0644"

- name: "Change user shell to ZSH"
  when: "'zsh' not in ansible_user_shell"
  expect:
    command: "chsh --shell /usr/bin/zsh"
    responses:
      Password: "{{ ansible_become_password }}"
