---

- name: "Install zsh and dependencies"
  when: "has_sudo"
  become: true
  ansible.builtin.package:
    name:
      - "zsh"
      - "git"
      - "curl"
      - "python-pexpect"

- name: "Check if zsh is installed"
  ansible.builtin.command: "which zsh"
  changed_when: false
  check_mode: false

- name: "Check if relevant applications are installed"
  vars:
    applications:
      - "ansible"
      - "docker"
      - "poetry"
      - "pip"
      - "sway"
  block:
    - name: "Check if application is installed"
      ansible.builtin.command: "which {{ item }}"
      register: "which_output"
      changed_when: false
      failed_when: false
      check_mode: false
      loop: "{{ applications }}"

    - name: "Set '_installed' boolean values"
      ansible.builtin.set_fact:
        "{{ item.item }}_installed": "{{ item.rc == 0 }}"
      loop: "{{ which_output.results }}"

- name: "Copy ZSH files"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    mode: "0644"
  loop:
    - "zlogin"

- name: "Copy ZSH template files"
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ ansible_user_dir }}/.{{ item }}"
    mode: "0644"
  loop:
    - "zshrc"
    - "zshenv"

- name: "Clone oh-my-zsh"
  ansible.builtin.git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/"
    version: "master"

- name: "Clone zsh-autosuggestions"
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions/"
    version: "master"

- name: "Copy theme"
  ansible.builtin.copy:
    src: "prompt.zsh-theme"
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/prompt.zsh-theme"
    mode: "0644"

- name: "Change user shell to ZSH"
  when: "'zsh' not in ansible_user_shell"
  ansible.builtin.>expect:
    command: "chsh --shell /usr/bin/zsh"
    responses:
      Password: "{{ ansible_become_password }}"
