---

- name: "Install NFS"
  become: yes
  package:
    name: "nfs-utils"

- name: "Copy exports"
  become: yes
  copy:
    src: "share.exports"
    dest: "/etc/exports.d/share.exports"
    owner: "root"
    group: "root"
    mode: "0644"

- name: "Start time sync daemon"
  become: yes
  systemd:
    name: "systemd-timesyncd"
    enabled: yes
    daemon_reload: yes

- name: "Start NFS server"
  become: yes
  systemd:
    name: "nfs-server"
    enabled: yes
    daemon_reload: yes
