---

- name: "Install git"
  pacman:
    name: "git"

- name: "Create Git config directory"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/git/"
    state: "directory"
    mode: "0755"

- name: "Copy git configuration files"
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/git/{{ item }}"
    mode: "0644"
  loop:
    - "config"
    - "attributes"
