call plug#begin('~/.vim/plug')
Plug 'rafi/awesome-vim-colorschemes'

Plug 'vim-airline/vim-airline'

let g:airline_powerline_fonts = 1
if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''

Plug 'w0rp/ale'

Plug 'airblade/vim-gitgutter'
set updatetime=100

Plug 'scrooloose/nerdtree'
map <C-n> :NERDTreeToggle<CR>

Plug 'lervag/vimtex'
let g:vimtex_view_general_viewer='zathura'
" It should be:
let g:vimtex_compiler_latexmk = {
    \ 'build_dir' : 'build',
    \}
call plug#end()

" Files
filetype plugin on
syntax on
set autoread
set noswapfile
set encoding=utf-8

" Visual
color nord
set ruler
set cursorline
set number
set relativenumber
set wildmenu
set showcmd
set laststatus=2
set mouse=a
set confirm
set visualbell
set cmdheight=2

" Editing
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set backspace=indent,eol,start
set nostartofline

" Searching
set hlsearch
set ignorecase
set smartcase
set incsearch
set showmatch

" Copying
set clipboard=unnamedplus

" Spellcheck
set spelllang=en,nl
nnoremap <F7> :setlocal spell! <CR>

"" Clear highlighting
nnoremap <C-L> :nohl<CR><C-L>

"" Save file as root with Sw
cnoremap w!! execute 'silent! write !sudo tee % >/dev/null' <bar> edit!<CR>

"" Move between buffers using Ctrl-Arrow
nnoremap <silent> <C-Right> <c-w>l
nnoremap <silent> <C-Left> <c-w>h
nnoremap <silent> <C-Up> <c-w>k
nnoremap <silent> <C-Down> <c-w>j
