---

- name: "Install Polybar dependencies"
  when: "has_sudo"
  become: yes
  pacman:
    name: "{{ packages_dependencies_polybar }}"
    state: "present"
    update_cache: yes

- name: "Create Polybar config directory"
  file:
    path: "{{ config_directory_polybar }}"
    state: "directory"

- name: "Copy polybar config"
  template:
    src: "config_polybar.j2"
    dest: "{{ config_directory_polybar }}/config"

- name: "Copy python scripts files"
  when: "has_sudo"
  become: yes
  copy:
    src: "scripts/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: "0755"
  loop:
    - "coinbase_usd_checker.py"
    - "spotify_info.py"
