---

- name: "Install packages"
  pacman:
    name:
      - "sudo"

- name: "Allow wheel group sudo permissions"
  become: true
  ansible.builtin.copy:
    src: "00-wheel"
    dest: "/etc/sudoers.d/00-wheel"
    mode: "0440"
    owner: "root"
    group: "root"
    validate: "visudo -cf %s"

- name: "Disable root password"
  become: true
  ansible.builtin.user:
    name: "root"
    password_lock: true

- name: "Disable locking user after 3 tries"
  become: true
  ansible.builtin.lineinfile:
    dest: "/etc/security/faillock.conf"
    regexp: '#? ?deny ?= ?\d+'
    line: "deny = 0"

- name: "Create main user"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    append: true
    groups:
      - "wheel"

- name: "Add user to adbusers group"
  when: "'android-tools' in packages_host"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "adbusers"
    append: true
