wallpaper_location: "{{ home_directory }}/wallpaper.jpg"
xresources_location: "{{ home_directory }}/.Xresources"

xorg_packages:
  - "xorg-server"
  - "xorg-server-devel"
  - "xorg-xset"
  - "xorg-apps"
  - "xorg-xrandr"
  - "xorg-xinit"
  - "xdg-utils"
  - "xterm"
  - "xf86-video-vesa"
  - "mesa"
  - "ttf-dejavu"
