---

- name: "Set hostname"
  become: yes
  hostname:
    name: "{{ inventory_hostname }}"

- name: "Disable root password"
  become: yes
  user:
    name: "root"
    password_lock: yes

- name: "Create plex user"
  become: yes
  user:
    name: "plex"
    comment: "Plex Media Server"
    uid: "976"
    state: "present"
    create_home: no

- name: "Set locale"
  become: yes
  block:
    - name: "Ensure en_US.UTF-8 exists"
      locale_gen:
        name: "en_US.UTF-8"
        state: "present"

    - name: "Ensure nl_NL.UTF-8 exists"
      locale_gen:
        name: "nl_NL.UTF-8"
        state: "present"

- name: "Disable SSH password logins"
  become: yes
  lineinfile:
    dest: "/etc/ssh/sshd_config"
    regexp: "^#?PasswordAuthentication (yes|no)$"
    line: "PasswordAuthentication no"
    state: "present"

- name: "Disable system beep"
  become: yes
  lineinfile:
    path: "/etc/modprobe.d/nobeep.conf"
    owner: "root"
    group: "root"
    mode: "0644"
    line: "blacklist pcspkr"
    state: "present"
    create: yes
