---

- name: "Set hostname"
  become: yes
  hostname:
    name: "{{ inventory_hostname }}"

- name: "Set locale"
  become: yes
  block:
    - name: "Ensure en_US.UTF-8 exists"
      locale_gen:
        name: "en_US.UTF-8"
        state: "present"

    - name: "Ensure nl_NL.UTF-8 exists"
      locale_gen:
        name: "nl_NL.UTF-8"
        state: "present"

- name: "Disable system beep"
  become: yes
  lineinfile:
    path: "/etc/modprobe.d/nobeep.conf"
    owner: "root"
    group: "root"
    mode: "0644"
    line: "blacklist pcspkr"
    state: "present"
    create: yes

- name: "Disable locking user after 3 tries"
  become: yes
  lineinfile:
    dest: "/etc/security/faillock.conf"
    regexp: '#? ?deny ?= ?\d+'
    line: "deny = 0"
    state: "present"

- name: "Update bootloader after update"
  become: yes
  systemd:
    name: "systemd-boot-update"
    state: "started"
    enabled: "yes"
