---

- name: "Set hostname"
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: "Set locale"
  become: true
  block:
    - name: "Ensure en_US.UTF-8 exists"
      community.general.locale_gen:
        name: "en_US.UTF-8"

    - name: "Ensure nl_NL.UTF-8 exists"
      community.general.locale_gen:
        name: "nl_NL.UTF-8"

- name: "Disable system beep"
  become: true
  ansible.builtin.lineinfile:
    path: "/etc/modprobe.d/nobeep.conf"
    owner: "root"
    group: "root"
    mode: "0644"
    line: "blacklist pcspkr"
    create: true

- name: "Update bootloader after update"
  become: true
  ansible.builtin.systemd:
    name: "systemd-boot-update"
    state: "started"
    enabled: true

- name: "Start time sync daemon"
  become: true
  ansible.builtin.systemd:
    name: "systemd-timesyncd"
    enabled: true
    daemon_reload: true

- name: "Start the fstrim timer"
  become: true
  ansible.builtin.systemd:
    name: "fstrim.timer"
    state: "started"
    enabled: true

- name: "Mount network share"
  become: true
  ansible.posix.mount:
    src: "meloen:/mnt/MainPool/share"
    path: "/mnt/share"
    fstype: "nfs"
    opts: "_netdev,x-systemd.automount"
    boot: false
    state: "present"
