---

- name: "Set hostname"
  become: yes
  hostname:
    name: "{{ inventory_hostname }}"

- name: "Disable root password"
  become: yes
  user:
    name: "root"
    password_lock: yes

- name: "Set locale"
  become: yes
  block:
    - name: "Ensure en_US.UTF-8 exists"
      locale_gen:
        name: "en_US.UTF-8"
        state: "present"

    - name: "Ensure nl_NL.UTF-8 exists"
      locale_gen:
        name: "nl_NL.UTF-8"
        state: "present"

- name: "Copy logind.conf"
  become: yes
  copy:
    src: "logind.conf"
    dest: "/etc/systemd/logind.conf"

- name: "Setup fonts"
  block:
    - name: "Install fonts"
      package:
        name: "ttf-dejavu"
        state: "present"

    - name: "Create .local/share/fonts/"
      file:
        path: "{{ ansible_user_dir }}/.local/share/fonts/"
        state: "directory"

    - name: "Install nerd font"
      get_url:
        url: "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/DejaVuSansMono/Regular/complete/DejaVu%20Sans%20Mono%20Nerd%20Font%20Complete%20Mono.ttf"
        dest: "{{ ansible_user_dir }}/.local/share/fonts/DejaVu Sans Mono Nerd Font Complete Mono.ttf"
