---

- name: "Install packages"
  become: true
  ansible.builtin.package:
    name:
      - "docker"
      - "docker-compose"
      - "python-docker"

- name: "Add user to docker group"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: "docker"
    append: true
