---

- name: "Install packages"
  become: yes
  package:
    name:
      - "docker"
      - "docker-compose"
      - "python-docker"

- name: "Add user to docker group"
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups: "docker"
    append: yes

- name: "Enable docker service"
  become: yes
  systemd:
    name: "docker"
    state: "started"
    enabled: yes

- name: "Setup a docker-compose project"
  when: "project is defined"
  include_tasks: "setup-docker-compose.yaml"
