---

- name: "Install dependencies"
  pacman:
    name:
      - "sway"
      - "swaylock"
      - "swayidle"
      - "grim"
      - "slurp"
      - "wl-clipboard"
      - "archlinux-wallpaper"
      - "playerctl"
      - "xorg-xwayland"

      # Fonts
      - "ttf-dejavu"
      - "adobe-source-code-pro-fonts"
      - "adobe-source-han-sans-otc-fonts"
      - "adobe-source-han-serif-otc-fonts"
      - "noto-fonts-emoji"

      # To list which applications are using XWayland
      - "xorg-xlsclients"

- name: "Setup audio"
  import_tasks: "setup-pipewire.yaml"
  tags:
    - "audio"
    - "pipewire"
    - "bluetooth"

- name: "Setup Wofi"
  import_tasks: "setup-wofi.yaml"
  tags:
    - "wofi"

- name: "Setup Alacritty"
  import_tasks: "setup-alacritty.yaml"
  tags:
    - "alacritty"

- name: "Setup Dunst"
  import_tasks: "setup-dunst.yaml"
  tags:
    - "dunst"

- name: "Setup Waybar"
  import_tasks: "setup-waybar.yaml"
  tags:
    - "waybar"

- name: "Create .config/sway/"
  file:
    path: "{{ ansible_user_dir }}/.config/sway/"
    state: "directory"
    mode: "0755"

- name: "Copy Sway config"
  template:
    src: "sway/config.j2"
    dest: "{{ ansible_user_dir }}/.config/sway/config"
    mode: "0644"
