---

- name: "Install dependencies"
  become: true
  community.general.pacman:
    name:
      - "sway"
      - "swaylock"
      - "swayidle"
      - "grim"
      - "slurp"
      - "wl-clipboard"
      - "archlinux-wallpaper"
      - "playerctl"
      - "xorg-xwayland"
      - "qt5-wayland"

      # Fonts
      - "ttf-firacode-nerd"
      - "noto-fonts-cjk"
      - "noto-fonts-emoji"
      - "noto-fonts-extra"
      - "noto-fonts"
      - "ttf-dejavu"

      # To list which applications are using XWayland
      - "xorg-xlsclients"

      # To run GUI applications as root
      - "xorg-xhost"

- name: "Setup audio"
  ansible.builtin.import_tasks: "setup-pipewire.yaml"
  tags:
    - "audio"
    - "pipewire"
    - "bluetooth"

- name: "Setup Wofi"
  ansible.builtin.import_tasks: "setup-wofi.yaml"
  tags:
    - "wofi"

- name: "Setup Alacritty"
  ansible.builtin.import_tasks: "setup-alacritty.yaml"
  tags:
    - "alacritty"

- name: "Setup Dunst"
  ansible.builtin.import_tasks: "setup-dunst.yaml"
  tags:
    - "dunst"

- name: "Setup Waybar"
  ansible.builtin.import_tasks: "setup-waybar.yaml"
  tags:
    - "waybar"
    - "swaynag"

- name: "Setup swaynag"
  ansible.builtin.import_tasks: "setup-swaynag.yaml"
  tags:
    - "swaynag"

- name: "Create .config/sway/"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/sway/"
    state: "directory"
    mode: "0755"

- name: "Copy Sway config"
  ansible.builtin.template:
    src: "sway/config.j2"
    dest: "{{ ansible_user_dir }}/.config/sway/config"
    mode: "0644"
