---

- name: "Install dependencies"
  pacman:
    name:
      - "waybar"
      - "light"
      - "dbus-python"
      - "otf-font-awesome"

- name: "Create necessary directories"
  file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: "directory"
    mode: "0755"
  loop:
    - ".local/bin/"
    - ".config/waybar/"

- name: "Copy config"
  copy:
    src: "waybar/config"
    dest: "{{ ansible_user_dir }}/.config/waybar/config"
    mode: "0644"

- name: "Copy style template"
  template:
    src: "waybar/style.css.j2"
    dest: "{{ ansible_user_dir }}/.config/waybar/style.css"
    mode: "0644"

- name: "Add user to video group"
  become: yes
  user:
    name: "{{ ansible_user }}"
    groups:
      - "video"
    append: yes

- name: "Copy python scripts files"
  copy:
    src: "scripts/{{ item }}"
    dest: "{{ ansible_user_dir }}/.local/bin/{{ item }}"
    mode: "0755"
  loop:
    - "coinbase_usd_checker.py"
    - "spotify_info.py"
