---

- name: "Create .config/swaynag/"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/swaynag/"
    state: "directory"
    mode: "0755"

- name: "Copy config"
  ansible.builtin.template:
    src: "swaynag/config.j2"
    dest: "{{ ansible_user_dir }}/.config/swaynag/config"
    mode: "0644"
