---

- name: "Install dependencies"
  become: true
  community.general.pacman:
    name:
      - "alacritty"

- name: "Create .config/alacritty/"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/alacritty/"
    state: "directory"
    mode: "0755"

- name: "Copy config template"
  ansible.builtin.template:
    src: "alacritty/alacritty.toml.j2"
    dest: "{{ ansible_user_dir }}/.config/alacritty/alacritty.toml"
    mode: "0644"
