---

- name: "Install dependencies"
  pacman:
    name:
      - "dunst"

- name: "Create .config/dunst/"
  file:
    path: "{{ ansible_user_dir }}/.config/dunst/"
    state: "directory"
    mode: "0755"

- name: "Copy templates"
  template:
    src: "dunst/dunstrc.j2"
    dest: "{{ ansible_user_dir }}/.config/dunst/dunstrc"
    mode: "0644"
