---

- name: "Install dependencies"
  community.general.pacman:
    name:
      - "waybar"
      - "otf-font-awesome"

- name: "Create necessary directories"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: "directory"
    mode: "0755"
  loop:
    - ".local/bin/"
    - ".config/waybar/"

- name: "Copy config"
  ansible.builtin.copy:
    src: "waybar/config"
    dest: "{{ ansible_user_dir }}/.config/waybar/config"
    mode: "0644"

- name: "Copy style template"
  ansible.builtin.template:
    src: "waybar/style.css.j2"
    dest: "{{ ansible_user_dir }}/.config/waybar/style.css"
    mode: "0644"

- name: "Add user to video group"
  become: true
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups:
      - "video"
    append: true

- name: "Copy python scripts files"
  ansible.builtin.copy:
    src: "scripts/{{ item }}"
    dest: "{{ ansible_user_dir }}/.local/bin/{{ item }}"
    mode: "0755"
  loop:
    - "coinbase_usd_checker.py"
