---

- name: "Install dependencies"
  become: true
  pacman:
    name:
      - "bluez"
      - "bluez-utils"
      - "blueman"
      - "pipewire-pulse"
      - "pipewire-alsa"
      - "pipewire-docs"
      - "wireplumber"
      - "xdg-desktop-portal-wlr"
      - "pavucontrol"

- name: "Enable bluetooth service"
  become: true
  systemd:
    name: "bluetooth"
    state: "started"
    enabled: true

- name: "Copy headset connection script"
  copy:
    src: "audio/headset.sh"
    dest: "{{ ansible_user_dir }}/.local/bin/headset.sh"
    mode: "0755"
