---

- name: "Install dependencies"
  pacman:
    name:
      - "alacritty"

- name: "Create .config/alacritty/"
  file:
    path: "{{ ansible_user_dir }}/.config/alacritty/"
    state: "directory"
    mode: "0755"

- name: "Copy templates"
  template:
    src: "alacritty/alacritty.yml.j2"
    dest: "{{ ansible_user_dir }}/.config/alacritty/alacritty.yml.j2"
    mode: "0644"
