---

- name: "Install Vim"
  when: "has_sudo"
  become: true
  ansible.builtin.package:
    name:
      - "neovim"
      - "vim"

- name: "Create directories"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: "directory"
    mode: "0755"
  loop:
    - ".config/nvim/"
    - ".local/share/nvim/site/autoload/"

- name: "Copy init.vim"
  ansible.builtin.copy:
    src: "init.vim"
    dest: "{{ ansible_user_dir }}/.config/nvim/init.vim"
    mode: "0644"

- name: "Install vim-plug"
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ ansible_user_dir }}/.local/share/nvim/site/autoload/plug.vim"
    mode: "0644"
