---
- name: "Install vim"
  when: "has_sudo"
  become: yes
  pacman:
    state: "present"
    name: "{{ package_vim|default('gvim') }}"
    update_cache: yes

- name: "Copy vimrc"
  template:
    src: "vimrc.j2"
    dest: "{{ ansible_user_dir }}/.vimrc"

- name: "Install vundle"
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    version: "master"
    dest: "{{ home_directory  }}/.vim/bundle/Vundle.vim"
    update: yes
