---

- name: "Install Vim"
  when: "has_sudo"
  become: yes
  package:
    state: "present"
    name:
      - "{{ package_vim }}"
      - "vim-spell-nl"

- name: "Check if Vim is installed"
  command: "which vim"
  changed_when: no
  check_mode: no

- name: "Create .vim/autoload directory"
  file:
    path: "{{ ansible_user_dir }}/.vim/autoload/"
    state: "directory"
    mode: "0755"

- name: "Copy .vimrc"
  copy:
    src: "vimrc"
    dest: "{{ ansible_user_dir }}/.vimrc"
    mode: "0644"

- name: "Install vim-plug"
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ ansible_user_dir }}/.vim/autoload/"

- name: "Install Vim plugins"
  command: "vim +PlugInstall +qall"
  changed_when: no
