---

name: "Linting"
on: ["push"]

jobs:
    ansible-lint:
        name: "Lint"
        runs-on: [self-hosted, windows]
        steps:
            - name: "Checkout repository"
              uses: "actions/checkout@v2"

            - uses: "actions/setup-python@v2"

            - name: "Install dependencies"
              run: "pip install --no-cache-dir --upgrade --quiet ansible-lint[community,yamllint] black"
