---

name: "Linting"
on: ["push"]

jobs:
    python:
        name: "Python"
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout repository"
              uses: "actions/checkout@v4"

            - name: "Disable Vault Password"
              run: "sed --in-place --expression 's/vault_password_file/# vault_password_file/' ansible.cfg"

            - name: "Install uv"
              uses: astral-sh/setup-uv@v5

            - name: "Set up Python"
              uses: "actions/setup-python@v5"
              with:
                  python-version-file: ".python-version"

            - name: "Install dependencies"
              run: "uv sync"

            - name: "Run ansible-lint"
              run: "uv run ansible-lint -q"

            - name: "Run ruff"
              run: "uv run ruff check"

            - name: "Run yamllint"
              run: "uv run yamllint --strict ."

            - name: Minimize uv cache
              run: "uv cache prune --ci"

    shell:
        name: "Shell"
        runs-on: "ubuntu-latest"
        steps:
            - name: "Checkout repository"
              uses: "actions/checkout@v4"

            - name: "Check for files with the yml extension"
              run: "if [[ -n $(find . -iname '*.yml') ]]; then exit 1; fi"

            - name: "Run shellcheck"
              run: "find . -type f -name '*.sh*' -exec shellcheck {} \\;"
